root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./starter serve"
  pre_cmd = ["templ generate -path ./ui", "bun run tw", "bun run js"]
  cmd = "go build -o starter ./main.go"
  delay = 1000
  exclude_dir = ["assets", "node_modules", "handle/build"]
  exclude_file = []
  exclude_regex = ["_test.go", "_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "templ", "html", "ts"]
  include_file = []
  kill_delay = "0s"
  poll = false
  poll_interval = 0
  post_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = true
# log = "build-errors.log"

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = true

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
